version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-mongo:/data/db

volumes:
  db-mongo:
